# Generated by Django 5.0.6 on 2024-06-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footwearimages',
        ),
        migrations.DeleteModel(
            name='Footwears',
        ),
    ]
