# Generated by Django 5.0.6 on 2024-06-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footwearimages',
            name='product',
        ),
        migrations.RemoveField(
            model_name='footwearimages',
            name='product_color',
        ),
        migrations.RemoveField(
            model_name='footwearimages',
            name='product_image',
        ),
        migrations.RemoveField(
            model_name='footwears',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='footwears',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='footwears',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='footwears',
            name='product_types',
        ),
    ]
