# Generated by Django 5.0.6 on 2024-06-14 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0006_remove_footwearimages_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footwearimages',
        ),
        migrations.DeleteModel(
            name='Footwears',
        ),
    ]
