# Generated by Django 5.0.6 on 2024-06-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('VolantApp', '0007_delete_footwearimages_delete_footwears'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footwears',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('sandals', 'sandals'), ('slipperandflipflops', 'slipperandflipflops'), ('casualshoes', 'casualshoes'), ('specialcollections', 'specialcollections'), ('flatshoes', 'flatshoes'), ('schooledition', 'schooledition')], max_length=100)),
                ('product_types', models.CharField(choices=[('ladies', 'ladies'), ('gents', 'gents'), ('boys', 'boys'), ('girls', 'girls'), ('kids', 'kids')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Footwearimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cherry', 'Cherry'), ('Gold', 'Gold'), ('Grape', 'Grape'), ('Green', 'Green'), ('Grey', 'Grey'), ('Maroon', 'Maroon'), ('Mehandi', 'Mehandi'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Peacock', 'Peacock'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Violet', 'Violet'), ('White', 'White'), ('Wine', 'Wine'), ('Yellow', 'Yellow')], max_length=100)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='imagesall/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwears')),
            ],
        ),
    ]
