# Generated by Django 5.0.6 on 2024-06-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0008_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwears',
            name='product_color',
            field=models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cherry', 'Cherry'), ('Gold', 'Gold'), ('Grape', 'Grape'), ('Green', 'Green'), ('Grey', 'Grey'), ('Maroon', 'Maroon'), ('Mehandi', 'Mehandi'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Peacock', 'Peacock'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Violet', 'Violet'), ('White', 'White'), ('Wine', 'Wine'), ('Yellow', 'Yellow')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
