# Generated by Django 5.0.6 on 2024-06-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0011_footwearsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='footwears',
            name='product_description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
