# Generated by Django 5.0.6 on 2024-06-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0012_footwears_product_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
