# Generated by Django 5.0.6 on 2024-06-19 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0013_delete_cartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('in_cart', 'in_cart'), ('order_placed', 'order_placed'), ('cancelled', 'cancelled')], default='in_cart', max_length=100)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwearimages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwears')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwearsize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
