# Generated by Django 5.0.6 on 2024-06-19 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0014_cartmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
