# Generated by Django 5.0.6 on 2024-06-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0016_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
