# Generated by Django 5.0.6 on 2024-06-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0017_alter_cartmodel_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwears',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
