# Generated by Django 5.0.6 on 2024-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0018_alter_footwears_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='total',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
    ]
