# Generated by Django 5.0.6 on 2024-06-20 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0019_cartmodel_total'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
