# Generated by Django 5.0.6 on 2024-06-20 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0020_delete_cartmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_color', models.CharField(choices=[('Black', 'Black'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Camel', 'Camel'), ('Cherry', 'Cherry'), ('Gold', 'Gold'), ('Grape', 'Grape'), ('Green', 'Green'), ('Grey', 'Grey'), ('Maroon', 'Maroon'), ('Mehandi', 'Mehandi'), ('Navy', 'Navy'), ('Olive', 'Olive'), ('Peach', 'Peach'), ('Peacock', 'Peacock'), ('Pink', 'Pink'), ('Purple', 'Purple'), ('Tan', 'Tan'), ('Violet', 'Violet'), ('White', 'White'), ('Wine', 'Wine'), ('Yellow', 'Yellow')], max_length=100)),
                ('size', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13')], max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('in_cart', 'in_cart'), ('order_placed', 'order_placed'), ('cancelled', 'cancelled')], default='in_cart', max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwears')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
