# Generated by Django 5.0.6 on 2024-06-20 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0021_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwearimages')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwears')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VolantApp.footwearsize')),
            ],
        ),
    ]
