# Generated by Django 5.0.6 on 2024-06-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0022_samplecart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='total',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='SampleCart',
        ),
    ]
