# Generated by Django 5.0.6 on 2024-06-21 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0023_alter_cartmodel_total_delete_samplecart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartModel',
        ),
    ]
