# Generated by Django 5.0.6 on 2024-06-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0025_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footwears',
            name='product_price',
            field=models.PositiveIntegerField(),
        ),
    ]
