# Generated by Django 5.0.6 on 2024-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0028_alter_cartmodel_quantity_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
