# Generated by Django 5.0.6 on 2024-06-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0029_alter_ordermodel_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('order-placed', 'order-placed'), ('cancelled', 'cancelled'), ('dispatched', 'dispatched')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
