# Generated by Django 5.0.6 on 2024-06-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolantApp', '0030_ordermodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('cancelled', 'cancelled'), ('order-placed', 'order-placed'), ('dispatched', 'dispatched')], default='order-placed', max_length=100),
        ),
    ]
